language: node_js
node_js: 
  - "10.11.0"
cache:
  directories:
    - "node_modules"
addons:
  ssh_known_hosts:
  - "128.199.230.238"
after_success:
  - git branch
  - git checkout master
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy # this key should have push access
  - ssh-add .travis/deploy
  - git remote add deploy root@128.199.230.238:/root/repo
  - git push deploy